### ISSUE TITLE
Please add a rename provider

### ISSUE THREAD

**Issue by martin-braun** [josa42/coc-sh#67]
I was installing this plugin in the hope to refactor variables in bash scripts, but it fails: 

```log
2022-11-03T05:11:18.756 INFO (pid:83223) [services] - LanguageClient bash-language-server state change: stopped => starting
2022-11-03T05:11:18.772 INFO (pid:83223) [language-client-index] - Language server "sh" started with 84503
2022-11-03T05:11:19.110 INFO (pid:83223) [attach] - receive notification: highlight []
2022-11-03T05:11:20.335 INFO (pid:83223) [attach] - receive notification: highlight []
2022-11-03T05:11:20.543 INFO (pid:83223) [services] - LanguageClient bash-language-server state change: starting => running
2022-11-03T05:11:20.544 INFO (pid:83223) [services] - service sh started
2022-11-03T05:11:21.852 INFO (pid:83223) [attach] - receive notification: rename []
2022-11-03T05:11:21.855 ERROR (pid:83223) [node-client] - Error on notification "rename": rename provider not found for current buffer, your language server doesn't support it. Error
    at eP.echoError (~/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:22:1869)
    at eP.<anonymous> (~/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:291:22439)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-03T05:11:21.855 ERROR (pid:83223) [attach] - Error: rename provider not found for current buffer, your language server doesn't support it.
    at Ey.checkProvier (~/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:291:8808)
    at py.rename (~/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:287:8285)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Ry.cocAction (~/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:291:20893)
    at async eP.<anonymous> (~/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:291:22402)
```

**Comment by Andrew15-5** [comment]
I'm also interested in this feature. Every time instead I have to `<C-n>` select every occurrence of a variable and batch rename it with multi cursor plugin.

**Comment by thi-marques** [comment]
It seems that [bash-language-server](https://github.com/bash-lsp/bash-language-server) community is already working on that.

See more on [#161](https://github.com/bash-lsp/bash-language-server/issues/161)

**Comment by martin-braun** [comment]
@thi-marques That's awesome, but I prefer to just use CoC plugins, since they are so much easier to setup and deal with. I hope this will be covered in coc-sh someday.

**Comment by josa42** [comment]
@martin-braun coc-sh is using [bash-language-server](https://github.com/bash-lsp/bash-language-server), renaming needs to be implemented there first.

**Comment by martin-braun** [comment]
@josa42 Thanks, I wasn't aware about this. Great, then it just needs to be implemented on https://github.com/bash-lsp/bash-language-server and we are good to go. 🙏
